// src/components/Navbar.tsx
import { useState } from 'react';
import { Menu, X, Mail } from 'lucide-react';
import { GithubIcon, LinkedinIcon } from './Icons';
import { useScrollPosition } from '../hooks/useScrollPosition';

interface NavbarProps {
  onNavigate: (id: string) => void;
}

const navLinks = [
  { id: 'home', label: 'Home' },
  { id: 'skills', label: 'Skills' },
  { id: 'projects', label: 'Projects' },
  { id: 'contact', label: 'Contact' },
] as const;

export function Navbar({ onNavigate }: NavbarProps) {
  const [isOpen, setIsOpen] = useState(false);
  const scrolled = useScrollPosition(50);

  const handleNav = (id: string) => {
    onNavigate(id);
    setIsOpen(false);
  };

  return (
    <nav
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 ${
        scrolled
          ? 'bg-surface/80 backdrop-blur-xl border-b border-white/5 shadow-lg shadow-primary/5'
          : 'bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16 lg:h-20">
          <button
            onClick={() => handleNav('home')}
            className="flex items-center gap-2 group"
            aria-label="Home"
          >
            <div className="w-9 h-9 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center font-bold text-white text-sm group-hover:shadow-lg group-hover:shadow-primary/50 transition-all duration-300">
              J
            </div>
            <span className="text-lg font-bold tracking-tight text-white">
              john<span className="text-primary-light">.</span>dev
            </span>
          </button>

          <div className="hidden md:flex items-center gap-1">
            {navLinks.map((link) => (
              <button
                key={link.id}
                onClick={() => handleNav(link.id)}
                className="px-4 py-2 rounded-lg text-sm font-medium text-slate-300 hover:text-white hover:bg-white/5 transition-all duration-300"
              >
                {link.label}
              </button>
            ))}
          </div>

          <div className="hidden md:flex items-center gap-3">
            <a
              href="https://github.com/momohbk"
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-all duration-300"
              aria-label="GitHub"
            >
              <GithubIcon />
            </a>
            <a
              href="https://www.linkedin.com/in/mohamed-boukahel-5508172a4/"
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-all duration-300"
              aria-label="LinkedIn"
            >
              <LinkedinIcon />
            </a>
            <button
              onClick={() => handleNav('contact')}
              className="ml-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-primary to-primary-dark text-white text-sm font-semibold hover:shadow-lg hover:shadow-primary/30 transition-all duration-300 hover:scale-105"
            >
              Get in Touch
            </button>
          </div>

          <button
            onClick={() => setIsOpen(!isOpen)}
            className="md:hidden p-2 rounded-lg text-slate-300 hover:text-white hover:bg-white/10 transition-all"
            aria-label={isOpen ? 'Close menu' : 'Open menu'}
            aria-expanded={isOpen}
          >
            {isOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>
      </div>

      {isOpen && (
        <div className="md:hidden bg-surface-light/95 backdrop-blur-xl border-t border-white/5 animate-fade-in-up">
          <div className="px-4 py-4 space-y-1">
            {navLinks.map((link) => (
              <button
                key={link.id}
                onClick={() => handleNav(link.id)}
                className="block w-full text-left px-4 py-3 rounded-lg text-sm font-medium text-slate-300 hover:text-white hover:bg-white/5 transition-all"
              >
                {link.label}
              </button>
            ))}
            <div className="flex items-center gap-3 pt-4 border-t border-white/10">
              <a href="https://github.com/momohbk" target="_blank" rel="noopener noreferrer" className="p-2 text-slate-400 hover:text-white" aria-label="GitHub">
                <GithubIcon />
              </a>
              <a href="https://www.linkedin.com/in/mohamed-boukahel-5508172a4/" target="_blank" rel="noopener noreferrer" className="p-2 text-slate-400 hover:text-white" aria-label="LinkedIn">
                <LinkedinIcon />
              </a>
              <a href="mailto:jboukahel14@gmail.com" className="p-2 text-slate-400 hover:text-white" aria-label="Email">
                <Mail className="w-5 h-5" />
              </a>
            </div>
          </div>
        </div>
      )}
    </nav>
  );
}

// projects/dinesync/frontend/src/components/Navbar.vue
<template>
  <nav class="bg-white shadow-sm border-b border-gray-100 sticky top-0 z-50">
    <div class="max-w-7xl mx-auto px-4">
      <div class="flex items-center justify-between h-16">
        <router-link to="/" class="flex items-center gap-2">
          <UtensilsCrossed class="w-6 h-6 text-brand-500" />
          <span class="text-xl font-display font-bold text-gray-900">DineSync</span>
        </router-link>

        <div class="hidden sm:flex items-center gap-6">
          <router-link
            v-for="link in links"
            :key="link.path"
            :to="link.path"
            class="text-sm font-medium text-gray-600 hover:text-brand-600 transition-colors"
            :class="{ 'text-brand-600': $route.path === link.path }"
          >
            {{ link.label }}
          </router-link>

          <router-link
            to="/reservations"
            class="bg-brand-500 hover:bg-brand-600 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            Book a Table
          </router-link>
        </div>

        <button
          class="sm:hidden p-2 rounded-lg text-gray-600 hover:bg-gray-100"
          @click="mobileOpen = !mobileOpen"
          aria-label="Toggle menu"
        >
          <Menu v-if="!mobileOpen" class="w-6 h-6" />
          <X v-else class="w-6 h-6" />
        </button>
      </div>

      <div v-if="mobileOpen" class="sm:hidden pb-4 space-y-2 animate-fade-in-up">
        <router-link
          v-for="link in links"
          :key="link.path"
          :to="link.path"
          class="block px-4 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-100"
          @click="mobileOpen = false"
        >
          {{ link.label }}
        </router-link>
        <router-link
          to="/reservations"
          class="block px-4 py-2 rounded-lg bg-brand-500 text-white text-sm font-medium text-center"
          @click="mobileOpen = false"
        >
          Book a Table
        </router-link>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { UtensilsCrossed, Menu, X } from 'lucide-vue-next';

const mobileOpen = ref(false);

const links = [
  { path: '/', label: 'Home' },
  { path: '/menu', label: 'Menu' },
  { path: '/admin', label: 'Admin' },
];
</script>
